
# Site settings
title: "ECG Recorder for Polar H10"
subtitle: "Saves data - displays live chart."
description: "Exports ECG, HR and RR data as text files and displays a live chart."
url: "https://poml88.github.io"
baseurl: "/ecg-recorder-ios"
screenshots_string: "Screenshots"

lang: "en"
app_icon: "/assets/img/app-icon.png"

# i18n data
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      image: "/assets/img/og-card.png"


# SEO plugin (allowed on GitHub Pages)
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude (optional)
exclude:
  - README.md
  - node_modules
  - vendor

# Paths for legal docs (German authoritative versions)
de_impressum_path: "/de/impressum.html"
de_privacy_path: "/de/datenschutzerklaerung.html"
