
# Site settings
title: "ECG Recorder App for Polar H10 (iOS)"
subtitle: "Record and export ECG, HR and RR data from Polar H10 bluetooth heart rate monitor with live chart on iPhone and iPad."
description: "Record ECG with Polar H10. Export ECG, heart rate (HR) and RR interval data as text files and view a live chart on iPhone and iPad."
url: "https://ecgh10.app"
baseurl: ""
screenshots_string: "Screenshots"

lang: "en"
app_icon: "/assets/img/app-icon.png"

# i18n data
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      image: "/assets/img/og-card.png"


# SEO plugin (allowed on GitHub Pages)
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude (optional)
exclude:
  - README.md
  - node_modules
  - vendor

# Paths for legal docs (German authoritative versions)
de_impressum_path: "/de/impressum.html"
de_privacy_path: "/de/datenschutzerklaerung.html"

webmaster_verifications:
  google: uxbdj6Qf78Bg-g_n5xNmOD9Opx9maZDQPAIGyfKLGgA
