title: ECG Recorder
description: Record and export single-lead ECGs on iPhone & iPad. Simple, private, and designed for clarity.
url: "https://poml88.github.io"
baseurl: "/ecg-recorder-ios"
timezone: Europe/Berlin

logo: /assets/img/app-icon.png
image: /assets/img/og.png

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Defaults set `lang` based on path
defaults:
  - scope:
      path: ""
    values:
      layout: default
      lang: en
  - scope:
      path: "de"
    values:
      lang: de
  - scope:
      path: "fr"
    values:
      lang: fr
  - scope:
      path: "zh-Hans"
    values:
      lang: zh-Hans
